name: Android Release APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      # 👉 Lavoriamo nella sottocartella del progetto
      - name: Install dependencies
        working-directory: ConvoyMeshApp
        run: flutter pub get

      # Rigeneriamo SOLO la piattaforma Android (Gradle, manifest, MainActivity, ecc.)
      # mantenendo il codice in lib/ così com'è.
      - name: Ensure Android platform exists
        working-directory: ConvoyMeshApp
        run: |
          rm -rf android
          flutter create . --platforms=android --project-name convoy_mesh_app --org app.convoymesh
          flutter pub get

      # Keystore temporaneo per firmare la release (va bene per test)
      - name: Generate throwaway keystore
        working-directory: ConvoyMeshApp
        run: |
          keytool -genkeypair -v -keystore release.keystore -storepass password -keypass password \
            -alias upload -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Convoy Mesh, O=Convoy, C=IT"
          echo "KEYSTORE_PATH=$(pwd)/release.keystore" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=password" >> $GITHUB_ENV
          echo "KEY_ALIAS=upload" >> $GITHUB_ENV
          echo "KEY_PASSWORD=password" >> $GITHUB_ENV

      # Abilita la firma release nel build.gradle generato
      - name: Enable release signing
        working-directory: ConvoyMeshApp
        run: |
          sed -i 's/minifyEnabled false/minifyEnabled false\n            signingConfig signingConfigs.release/g' android/app/build.gradle
          # Patcha la sezione signingConfigs.release
          sed -i 's/signingConfigs {[^}]*}/signingConfigs {\n        release {\n            storeFile file("'"$KEYSTORE_PATH"'")\n            storePassword "'"$KEYSTORE_PASSWORD"'"\n            keyAlias "'"$KEY_ALIAS"'"\n            keyPassword "'"$KEY_PASSWORD"'"\n        }\n    }/g' android/app/build.gradle

      - name: Build release APK
        working-directory: ConvoyMeshApp
        run: flutter build apk --release

      - name: List outputs
        working-directory: ConvoyMeshApp
        run: ls -R build/app/outputs || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: convoy-mesh-release
          path: ConvoyMeshApp/build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
